import { Nunito } from "next/font/google";
import { Navbar } from "./components/Navbar";
import "./globals.css";

import { RegisterModal } from "./components/modals/RegisterModal";
import { ToasterProvider } from "./providers/ToasterProvider";
import { LoginModal } from "./components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Airbnb - @danniiigt",
  description: "Generated by create next app",
  favicon: "/favicon.ico",
};

export default async function RootLayout({ children }) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* PROVIDERS */}
        <ToasterProvider />

        {/* MODALS */}
        <RegisterModal />
        <LoginModal />

        {/* COMPONENTS */}
        <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
